/**************************************
    Webutler V2.1 - www.webutler.de
    Copyright (c) 2008 - 2011
    Autor: Sven Zinke
    Free for any use
    Lizenz: GPL
**************************************/

(function(){CKEDITOR.plugins.add('lightbox',{lang:[CKEDITOR.lang.detect(CKEDITOR.config.language)]});CKEDITOR.on('dialogDefinition',function(a){var b=a.data.name,c=a.data.definition,d=a.editor;if(b=='image'){function e(h){try{var i=h.getSelection();if(i.getType()==CKEDITOR.SELECTION_ELEMENT){var j=i.getSelectedElement();if(j.is('a'))return j;}var k=i.getRanges(true)[0];k.shrink(CKEDITOR.SHRINK_TEXT);var l=k.getCommonAncestor();return l.getAscendant('a',true);}catch(m){return null;}};function f(){var h=CKEDITOR.dialog.getCurrent(),i=h.getContentElement('info','BoxZoom');NextField=h.getContentElement('info','BoxNext'),NumField=h.getContentElement('info','BoxNum'),RelField=h.getContentElement('info','BoxRel');var j='';if(i.getValue()==true){j='lightbox';if(NextField.getValue()==true&&NumField.getValue()!='')j+=NumField.getValue();RelField.setValue(j);}else RelField.setValue('');};var g=c.getContents('info');g.add({type:'vbox',padding:0,children:[{type:'html',html:d.lang.lightbox.title},{type:'hbox',style:'margin:0px;width:100px;vertical-align: middle;',children:[{type:'html',html:d.lang.lightbox.imgzoom,style:'display:block;margin-top:3px;'},{type:'checkbox',id:'BoxZoom',label:' ','default':'',style:'margin-right:5px;padding:0px',onChange:function(){var h=CKEDITOR.dialog.getCurrent(),i=h.getContentElement('info','txtUrl'),j=h.getContentElement('info','BoxNext'),k=h.getContentElement('info','BoxNum'),l=h.getContentElement('Link','txtUrl'),m=i.getValue(),n;if(m!=''){var o=m.substr(m.lastIndexOf('/')+1),p=m.substring(0,m.lastIndexOf('/'));n=p+'/.box/'+o;}if(i.getValue()=='')this.setValue(false,'change');if(this.getValue()==false){if(j.getValue()==true)j.setValue(false,'change');k.setValue('');l.setValue('');}else l.setValue(n);f();},onShow:function(){var h=CKEDITOR.dialog.getCurrent(),i=h.getContentElement('info','txtUrl'),j=h.getContentElement('Link','txtUrl'),k=i.getValue();orgLinkField=j.getValue();if(k!=''){var l=k.substr(k.lastIndexOf('/')+1),m=k.substring(0,k.lastIndexOf('/')),n=m+'/.box/'+l;}if(orgLinkField==n)this.setValue(true,'change');else this.setValue(false,'change');}},{type:'html',html:d.lang.lightbox.browse,style:'display:block;margin-top:3px;'},{type:'checkbox',id:'BoxNext',label:' ','default':'',style:'margin-right:5px;padding:0px',onClick:function(){var h=CKEDITOR.dialog.getCurrent(),i=h.getContentElement('info','BoxZoom'),j=h.getContentElement('info','BoxNum');if(i.getValue()==false&&this.getValue()==true)this.setValue(false,'change');if(this.getValue()==false)j.setValue('');
else j.setValue('1');f();}},{type:'html',html:d.lang.lightbox.boxnum+':',style:'display:block;margin-top:3px;'},{type:'text',id:'BoxNum',label:' ','default':'',style:'width:25px',validate:CKEDITOR.dialog.validate.integer(d.lang.lightbox.mustint),onKeyUp:function(){var h=CKEDITOR.dialog.getCurrent(),i=h.getContentElement('info','BoxZoom'),j=h.getContentElement('info','BoxNext');if(i.getValue()==false||j.getValue()==false)this.setValue('');if(i.getValue()!=false&&j.getValue()!=false&&this.getValue()<=0)this.setValue('1');f();}},{type:'text',id:'BoxRel',label:'','default':'',style:'display: none',onHide:function(){this.setValue('');},setup:function(){var h=e(d);if(h){this.setValue(h.getAttribute('rel')||'');var i=CKEDITOR.dialog.getCurrent(),j=i.getContentElement('Link','txtUrl'),k=j.getValue(),l=i.getContentElement('info','BoxZoom'),m=i.getContentElement('info','BoxNext'),n=i.getContentElement('info','BoxNum');if(k!=''&&this.getValue()!=''){var o=this.getValue();relLight=o.substring(0,8);if(relLight=='lightbox'){l.setValue(true,'change');relNr=o.substr(8);if(relNr!=''){m.setValue(true,'change');n.setValue(relNr);}}}}},commit:function(){var h=this;if(h.getValue()!=''){h.linkElement=h.getDialog().linkElement;h.linkElement.setAttribute('rel',h.getValue());}}}]}]},'txtAlt');}});})();
